---
name: Tag Versioning

on:  # yamllint disable-line rule:truthy
  release:
    types:
      - published
      - edited

permissions: {}

jobs:
  actions-tagger:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: Actions-R-Us/actions-tagger@f411bd910a5ad370d4511517e3eac7ff887c90ea # v2.0.2
